title: James Portier # your name (or website title) here
logo: "/images/me.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my personal website! I am a final year MMath Mathematics student at the University of St. Andrew's, with a strong passion for data science and quantitative analysis. Throughout my studies I have cultivated 
  robust mathematical skills, complemented by strong coding proficiency in Python and R.
  <br><br>
  This website serves as a platform to showcase the various data science and quant coding projects I have completed over the summer, along with highlighting the online courses I have undertaken.
  <br><br>
  <a href="https://www.linkedin.com/in/james-portier">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - arimaQuantconnect.md
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

