title: James Portier # your name (or website title) here
logo: "/images/meNew.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my portfolio! I am currently a Quantitative Analyst at a leading commodity research firm in London, specialising in modelling financial flows within the options and futures markets. I hold a First-Class Honours degree in MMath Mathematics from the University of St. Andrews. Here, you'll find a selection of my key projects, including those completed outside of coursework, as well as my Master's thesis. 
  <br><br>
  <a href="https://www.linkedin.com/in/james-portier">View My LinkedIn Profile</a> 
  
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-SB0M4X791N # your Google Analytics tracking ID here

