title: James Portier # your name (or website title) here
logo: "/images/meNew.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my portfolio! I'm currently working as Quantitative Analyst in London for a commodity research firm, having graduated from the University of St. Andrews in MMath Mathematics with First Class Honours. Here I showcase projects I worked on outside of class as well as my Master's Thesis. 
  <br><br>
  <a href="https://www.linkedin.com/in/james-portier">View My LinkedIn Profile</a> 
  
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-SB0M4X791N # your Google Analytics tracking ID here

